In [1]:
import numpy as np

In [2]:
a  = np.array([5,6,9])
a[0]

5

In [3]:
print(a[0])

5


In [4]:
a.ndim

1

In [6]:
a = np.array([[1,2],[3,4],[5,6]])
a.ndim

2

In [7]:
a.itemsize

4

In [8]:
a.dtype

dtype('int32')

In [9]:
a = np.array([[1,2],[3,4],[5,6]], dtype=np.float64)

In [10]:
a.itemsize

8

In [11]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [14]:
print(a.size)

6


In [13]:
a.shape

(3, 2)

In [15]:
a = np.array([[1,2],[3,4],[5,6]], dtype=complex)

In [16]:
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [17]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
l= range(5)
l

range(0, 5)

In [22]:
l[4]

4

In [23]:
np.arange(1,5)

array([1, 2, 3, 4])

In [24]:
np.arange(1,5,2)

array([1, 3])

In [25]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [26]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [27]:
a = np.array([[1,2],[3,4],[5,6]])
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [29]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
a.min()

1

In [31]:
a.sum()

21

In [32]:
a.sum(axis=0)

array([ 9, 12])

In [33]:
a.sum(axis=1)

array([ 3,  7, 11])

In [34]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [35]:
np.std(a)

1.707825127659933

In [36]:
a = np.array([[1,2],[3,4]])
b= np.array([[5,6],[7,8]])

In [37]:
a+b

array([[ 6,  8],
       [10, 12]])

In [38]:
a*b

array([[ 5, 12],
       [21, 32]])

In [39]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [40]:
a.dot(b)

array([[19, 22],
       [43, 50]])